/**
 * Copyright (c) 2026-2026 HiSilicon (Shanghai) Technologies Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#include "app_init.h"
#include "osal_debug.h"
#include "common_def.h"
#include "cmsis_os2.h"
#include "securec.h"
#include "tcxo.h"
#include "watchdog.h"
#include "ai.h"
#include "mnist_training_data.h"

/* Task Param */
#define TASKS_MCU_AI_STACK_SIZE 0x2000
#define TASKS_MCU_AI_PRIO (osPriority_t)(17)
#define TASKS_MCU_AI_TICKS_PER_SECOND 24000
#define TASKS_MCU_AI_PRINT_FLOAT_MULTIPILER 100000

#define AI_MCU_SAMPLE_LOG_TAG "[MNIST_TRAIN] "
#define AI_MCU_SAMPLE_LOGITS_SIZE 10
#define AI_MCU_SAMPLE_PREDICT_INDEX 6
/* Run evaluation after this many training steps. */
#define AI_MCU_SAMPLE_EVAL_INTERVAL_STEPS 100

enum {
    /* RunStep outputs are fixed for this training model: logits first, loss second. */
    AI_MCU_SAMPLE_OUTPUT_LOGITS = 0,
    AI_MCU_SAMPLE_OUTPUT_LOSS = 1,
};

struct ai_mcu_param {
    OH_AI_ModelHandle model;
    OH_AI_ContextHandle context;
    OH_AI_TensorHandleArray inputs;
    OH_AI_TensorHandleArray labels;
    OH_AI_TensorHandleArray outputs;
};

static void ai_mcu_sample_printf_float(float value)
{
    int scaled = (int)(value * TASKS_MCU_AI_PRINT_FLOAT_MULTIPILER);
    if (scaled < 0) {
        osal_printk("-");
        scaled = -scaled;
    }
    osal_printk("%d.%05d", scaled / TASKS_MCU_AI_PRINT_FLOAT_MULTIPILER, scaled % TASKS_MCU_AI_PRINT_FLOAT_MULTIPILER);
}

static OH_AI_Status ai_mcu_sample_copy_tensor(OH_AI_TensorHandle tensor, const void *data, size_t data_size)
{
    if (tensor == NULL || data == NULL) {
        return OH_AI_STATUS_FAILED;
    }
    void *tensor_data = OH_AI_TensorGetMutableData(tensor);
    if (tensor_data == NULL) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "OH_AI_TensorGetMutableData failed\n");
        return OH_AI_STATUS_FAILED;
    }
    if (memcpy_s(tensor_data, data_size, data, data_size) != EOK) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "memcpy_s failed\n");
        return OH_AI_STATUS_FAILED;
    }
    return OH_AI_STATUS_SUCCESS;
}

static OH_AI_Status ai_mcu_sample_load_input(OH_AI_TensorHandle tensor, const uint8_t *sample_data)
{
    const float input_scale = 255.0f;

    if (tensor == NULL || sample_data == NULL) {
        return OH_AI_STATUS_FAILED;
    }
    float *tensor_data = (float *)OH_AI_TensorGetMutableData(tensor);
    if (tensor_data == NULL) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "OH_AI_TensorGetMutableData failed\n");
        return OH_AI_STATUS_FAILED;
    }
    for (size_t i = 0; i < AI_MCU_SAMPLE_INPUT_1_SIZE; ++i) {
        tensor_data[i] = (float)sample_data[i] / input_scale;
    }
    return OH_AI_STATUS_SUCCESS;
}

static OH_AI_Status ai_mcu_sample_load_batch(struct ai_mcu_param *sample_param, const uint8_t *sample_data,
                                             const int32_t *label)
{
    /*
     * Training and evaluation consume both model input and label. The label is
     * not part of GetInputs(); it is exposed separately through GetLabels()
     * because Predict does not need supervised loss information.
     */
    OH_AI_Status ret = ai_mcu_sample_load_input(sample_param->inputs.handle_list[0], sample_data);
    if (ret != OH_AI_STATUS_SUCCESS) {
        return ret;
    }
    return ai_mcu_sample_copy_tensor(sample_param->labels.handle_list[0], label,
                                     AI_MCU_SAMPLE_LABEL_SIZE * sizeof(int32_t));
}

static int32_t ai_mcu_sample_argmax_logits(const float *logits)
{
    int32_t max_index = 0;
    float max_value = logits[0];
    for (int32_t i = 1; i < AI_MCU_SAMPLE_LOGITS_SIZE; ++i) {
        if (logits[i] > max_value) {
            max_value = logits[i];
            max_index = i;
        }
    }
    return max_index;
}

static OH_AI_Status ai_mcu_sample_get_loss(OH_AI_TensorHandleArray outputs, float *loss)
{
    /*
     * Loss is generated by RunStep. Predict is the pure inference path and only
     * writes logits, so callers must read loss only after eval/train RunStep.
     */
    if (loss == NULL || outputs.handle_list[AI_MCU_SAMPLE_OUTPUT_LOSS] == NULL) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "loss output is unavailable\n");
        return OH_AI_STATUS_FAILED;
    }
    void *data = OH_AI_TensorGetMutableData(outputs.handle_list[AI_MCU_SAMPLE_OUTPUT_LOSS]);
    if (data == NULL) {
        return OH_AI_STATUS_FAILED;
    }
    *loss = ((float *)data)[0];
    return OH_AI_STATUS_SUCCESS;
}

static OH_AI_Status ai_mcu_sample_predict(struct ai_mcu_param *sample_param)
{
    /*
     * Predict demonstrates the inference path. It only feeds input data and does
     * not set labels, compute loss, or update trainable weights.
     */
    OH_AI_Status ret =
        ai_mcu_sample_load_input(sample_param->inputs.handle_list[0], g_mnist_eval_inputs[AI_MCU_SAMPLE_PREDICT_INDEX]);
    if (ret != OH_AI_STATUS_SUCCESS) {
        return ret;
    }

    /*
     * The training model owns two stable outputs: logits and loss. Predict only
     * writes logits, so pass a one-output view that hides the trailing loss.
     */
    OH_AI_TensorHandleArray predict_outputs = {
        .handle_num = 1,
        .handle_list = sample_param->outputs.handle_list,
    };
    uint64_t start = uapi_tcxo_get_count();
    ret = OH_AI_ModelPredict(sample_param->model, sample_param->inputs, &predict_outputs);
    uint64_t end = uapi_tcxo_get_count();
    if (ret != OH_AI_STATUS_SUCCESS) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "OH_AI_ModelPredict failed (%d)\n", ret);
        return ret;
    }
    float *logits = (float *)OH_AI_TensorGetMutableData(predict_outputs.handle_list[AI_MCU_SAMPLE_OUTPUT_LOGITS]);
    if (logits == NULL) {
        return OH_AI_STATUS_FAILED;
    }
    int32_t pred = ai_mcu_sample_argmax_logits(logits);
    osal_printk(AI_MCU_SAMPLE_LOG_TAG "Prediction\n");
    osal_printk(AI_MCU_SAMPLE_LOG_TAG "  pred: %d\n", pred);
    osal_printk(AI_MCU_SAMPLE_LOG_TAG "  time: %dms\n", ((int)end - (int)start) / TASKS_MCU_AI_TICKS_PER_SECOND);
    osal_printk(AI_MCU_SAMPLE_LOG_TAG "  logits: ");
    osal_printk("[");
    for (int32_t i = 0; i < AI_MCU_SAMPLE_LOGITS_SIZE; ++i) {
        if (i > 0) {
            osal_printk(", ");
        }
        ai_mcu_sample_printf_float(logits[i]);
    }
    osal_printk("]\n");
    osal_printk(AI_MCU_SAMPLE_LOG_TAG "\n");
    return OH_AI_STATUS_SUCCESS;
}

static OH_AI_Status ai_mcu_sample_run_steps(struct ai_mcu_param *sample_param,
                                            const uint8_t (*inputs)[AI_MCU_SAMPLE_INPUT_1_SIZE],
                                            const int32_t *labels, size_t count, bool print_metrics)
{
    /*
     * SetTrainMode is handled by the caller. This helper only loads one sample,
     * calls RunStep, and optionally prints loss/accuracy metrics.
     */
    OH_AI_Status ret;
    float loss_sum = 0.0f;
    int32_t correct = 0;
    for (size_t i = 0; i < count; ++i) {
        ret = ai_mcu_sample_load_batch(sample_param, inputs[i], &labels[i]);
        if (ret != OH_AI_STATUS_SUCCESS) {
            return ret;
        }
        ret = OH_AI_ModelRunStep(sample_param->model);
        if (ret != OH_AI_STATUS_SUCCESS) {
            osal_printk(AI_MCU_SAMPLE_LOG_TAG "OH_AI_ModelRunStep failed (%d)\n", ret);
            return ret;
        }
        if (print_metrics) {
            float loss = 0.0f;
            ret = ai_mcu_sample_get_loss(sample_param->outputs, &loss);
            if (ret != OH_AI_STATUS_SUCCESS) {
                return ret;
            }
            float *logits =
                (float *)OH_AI_TensorGetMutableData(sample_param->outputs.handle_list[AI_MCU_SAMPLE_OUTPUT_LOGITS]);
            if (logits == NULL) {
                return OH_AI_STATUS_FAILED;
            }
            loss_sum += loss;
            correct += ai_mcu_sample_argmax_logits(logits) == labels[i] ? 1 : 0;
        }
        /* Dataset loops can exceed the watchdog timeout, so kick it periodically to avoid a board reset. */
        (void)uapi_watchdog_kick();
    }

    if (print_metrics) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "  avg loss: ");
        ai_mcu_sample_printf_float(loss_sum / (float)count);
        osal_printk("\n");
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "  accuracy: %d/%u\n", correct, (unsigned int)count);
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "\n");
    }

    return OH_AI_STATUS_SUCCESS;
}

static OH_AI_Status ai_mcu_sample_eval_steps(struct ai_mcu_param *sample_param)
{
    /* Eval uses RunStep with train mode disabled. It runs forward + loss. */
    OH_AI_Status ret = OH_AI_ModelSetTrainMode(sample_param->model, false);
    if (ret != OH_AI_STATUS_SUCCESS) {
        return ret;
    }
    return ai_mcu_sample_run_steps(sample_param, g_mnist_eval_inputs, g_mnist_eval_labels,
                                   AI_MCU_SAMPLE_EVAL_DATASET_SIZE, true);
}

static OH_AI_Status ai_mcu_sample_train_steps(struct ai_mcu_param *sample_param)
{
    size_t trained_steps = 0;
    while (trained_steps < AI_MCU_SAMPLE_TRAIN_DATASET_SIZE) {
        size_t remaining_steps = AI_MCU_SAMPLE_TRAIN_DATASET_SIZE - trained_steps;
        size_t steps_this_round =
            remaining_steps < AI_MCU_SAMPLE_EVAL_INTERVAL_STEPS ? remaining_steps : AI_MCU_SAMPLE_EVAL_INTERVAL_STEPS;
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "Training (steps %u-%u)\n", (unsigned int)(trained_steps + 1),
                    (unsigned int)(trained_steps + steps_this_round));
        /*
         * Train uses RunStep with train mode enabled. In this mode RunStep runs
         * forward + loss + backward + optimizer update.
         */
        OH_AI_Status ret = OH_AI_ModelSetTrainMode(sample_param->model, true);
        if (ret != OH_AI_STATUS_SUCCESS) {
            return ret;
        }
        ret = ai_mcu_sample_run_steps(sample_param, &g_mnist_train_inputs[trained_steps],
                                      &g_mnist_train_labels[trained_steps], steps_this_round, false);
        if (ret != OH_AI_STATUS_SUCCESS) {
            return ret;
        }
        trained_steps += steps_this_round;

        if ((trained_steps % AI_MCU_SAMPLE_EVAL_INTERVAL_STEPS) == 0 ||
            trained_steps == AI_MCU_SAMPLE_TRAIN_DATASET_SIZE) {
            osal_printk(AI_MCU_SAMPLE_LOG_TAG "Evaluation (after %u training steps)\n", (unsigned int)trained_steps);
            ret = ai_mcu_sample_eval_steps(sample_param);
            if (ret != OH_AI_STATUS_SUCCESS) {
                return ret;
            }
        }
    }
    return OH_AI_STATUS_SUCCESS;
}

static OH_AI_Status ai_mcu_sample_init(struct ai_mcu_param *sample_param)
{
    OH_AI_Status ret = OH_AI_Init(NULL, 0);
    if (ret != OH_AI_STATUS_SUCCESS) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "OH_AI_Init failed (%d)\n", ret);
        return ret;
    }
    sample_param->model = OH_AI_ModelCreate();
    sample_param->context = OH_AI_ContextCreate();
    if (sample_param->model == NULL || sample_param->context == NULL) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "create model/context failed\n");
        return OH_AI_STATUS_FAILED;
    }
    ret = OH_AI_ModelBuild(sample_param->model, NULL, 0, sample_param->context);
    if (ret != OH_AI_STATUS_SUCCESS) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "OH_AI_ModelBuild failed (%d)\n", ret);
        return ret;
    }
    /*
     * LoadWeight(0) copies default weights into the internal RAM weight area.
     * Training updates this RAM copy.
     */
    ret = OH_AI_ModelLoadWeight(sample_param->model, 0);
    if (ret != OH_AI_STATUS_SUCCESS) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "OH_AI_ModelLoadWeight failed (%d)\n", ret);
        return ret;
    }
    /*
     * Inputs are used by Predict/RunStep. Labels are separate tensors used only
     * by eval/train loss computation. Outputs are stable after Build:
     * output 0 is logits, output 1 is loss.
     */
    sample_param->inputs = OH_AI_ModelGetInputs(sample_param->model);
    sample_param->labels = OH_AI_ModelGetLabels(sample_param->model);
    /*
     * The training model exposes stable outputs after Build:
     * output 0 is logits, output 1 is loss. Predict uses a local view that
     * hides the trailing loss tensor, while eval/train both consume it.
     */
    sample_param->outputs = OH_AI_ModelGetOutputs(sample_param->model);
    if (sample_param->inputs.handle_list == NULL || sample_param->labels.handle_list == NULL ||
        sample_param->outputs.handle_list == NULL) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "get model tensors failed\n");
        return OH_AI_STATUS_FAILED;
    }
    return OH_AI_STATUS_SUCCESS;
}

static void ai_mcu_sample_destroy(struct ai_mcu_param *sample_param)
{
    if (sample_param->model != NULL) {
        OH_AI_ModelDestroy(&(sample_param->model));
    }
    if (sample_param->context != NULL) {
        OH_AI_ContextDestroy(&(sample_param->context));
    }
    (void)OH_AI_Deinit();
}

static void *ai_mcu_task(const char *arg)
{
    unused(arg);
    struct ai_mcu_param sample_param = { 0 };
    OH_AI_Status ret = ai_mcu_sample_init(&sample_param);
    if (ret != OH_AI_STATUS_SUCCESS) {
        goto exit;
    }
    /* Use one fixed eval sample before and after training to show how logits change. */
    ret = ai_mcu_sample_predict(&sample_param);
    if (ret != OH_AI_STATUS_SUCCESS) {
        goto exit;
    }

    osal_printk(AI_MCU_SAMPLE_LOG_TAG "Evaluation (before training)\n");
    ret = ai_mcu_sample_eval_steps(&sample_param);
    if (ret != OH_AI_STATUS_SUCCESS) {
        goto exit;
    }

    ret = ai_mcu_sample_train_steps(&sample_param);
    if (ret != OH_AI_STATUS_SUCCESS) {
        goto exit;
    }
    /* Run the same prediction again after training. */
    ret = ai_mcu_sample_predict(&sample_param);
    if (ret != OH_AI_STATUS_SUCCESS) {
        goto exit;
    }

exit:
    if (ret != OH_AI_STATUS_SUCCESS) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "Task failed (%d)\n", ret);
    }
    ai_mcu_sample_destroy(&sample_param);
    return NULL;
}

static void tasks_test_entry(void)
{
    osal_printk(AI_MCU_SAMPLE_LOG_TAG "task entry\n");
    osThreadAttr_t attr;
    attr.name = "AI_MCU_Task";
    attr.attr_bits = 0U;
    attr.cb_mem = NULL;
    attr.cb_size = 0U;
    attr.stack_mem = NULL;
    attr.stack_size = TASKS_MCU_AI_STACK_SIZE;
    attr.priority = TASKS_MCU_AI_PRIO;

    if (osThreadNew((osThreadFunc_t)ai_mcu_task, NULL, &attr) == NULL) {
        osal_printk(AI_MCU_SAMPLE_LOG_TAG "task create failed\n");
    }
}

app_run(tasks_test_entry);
